name: stencil-template-base
arguments:
  description: Stencil template repository for template repositories
  oss: true
  reportingTeam: fnd-dt
  releaseOptions:
    allowMajorVersions: true
modules:
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/stencil-template-base

# We run ourself on... ourself :D
replacements:
  github.com/getoutreach/stencil-template-base: ./
