name: stencil-template-base
arguments:
  description: Stencil template repository for template repositories
  oss: true
  reportingTeam: fnd-dt
  releaseOptions:
    enablePrereleases: true
    prereleasesBranch: rc
modules:
  - name: github.com/getoutreach/stencil-template-base
  - name: github.com/getoutreach/stencil-base
  - name: github.com/getoutreach/stencil-circleci
  - name: github.com/getoutreach/devbase
    channel: rc

# We run ourself on... ourself :D
replacements:
  github.com/getoutreach/stencil-template-base: ./
